
float temp_storage;
float humid_storage;


#define SEALEVELPRESSURE_HPA (1013.25)
Adafruit_BME280 bme;
bool bme_found;

int polling_rate = 5; // Number of seconds between polling bme280 attempts
int loop_iter;

const char* mqttServerIp = "";
const short mqttServerPort = 1883;
const char* mqttUsername = "";
const char* mqttPassword = "";
#define ClientName "ir_blaster"
/// the following topics are generated by preprocessor using the client name
const char *mqttClientName = ClientName;
const char* mqtt_data_topic = ClientName "/bme280";
const char *json_command_topic = ClientName "/command";
const char *mqtt_log_topic = ClientName "/logs";
const char *willTopic = ClientName "/status";
const char *willMessage = "offline";

int mqtt_failed_connection_attempts;
int willQoS = 1;
int willRetain = 1;
bool wasConnected = 0;


char *ssid      = "";               // Set you WiFi SSID
char *password  = "";               // Set you WiFi password

WiFiClient espClient;
PubSubClient mqtt_client(espClient);

WiFiUDP ntpUDP;
NTPClient timeClient(ntpUDP, "", 3600, 60000);

const uint16_t kIrLed = 4;  // ESP8266 GPIO pin to use. Recommended: 4 (D2).
IRsend irsend(kIrLed);  // Set the GPIO to be used to sending the message.
